#!/bin/sh

 NAME1=bibauthor
 NAME2=bibmaint

 UTILFILE=util
 DATABASE=cs348

 DB2HOME=`eval echo ~"$DB2INSTANCE"`
 DB2PATH="$DB2HOME"/sqllib

 CC=gcc
 CFLAGS=-I"$DB2PATH"/include
 LIBS="-L$DB2PATH/lib -ldb2"

 set -x

 rm -f "$NAME1" "$NAME1".c "$NAME1".o "$NAME1".bnd
 rm -f "$NAME2" "$NAME2".c "$NAME2".o "$NAME2".bnd
 rm -f "$UTILFILE" "$UTILFILE".o "$UTILFILE".bnd

 db2 connect to "$DATABASE"
 db2 prep "$NAME1".sqc bindfile
 db2 bind "$NAME1".bnd
 db2 connect reset
 "$CC" "$CFLAGS" -c "$NAME1".c
 "$CC" "$CFLAGS" -c "$UTILFILE".c
 "$CC" "$CFLAGS" -o "$NAME1" "$NAME1".o "$UTILFILE".o $LIBS

 db2 connect to "$DATABASE"
 db2 prep "$NAME2".sqc bindfile
 db2 bind "$NAME2".bnd
 db2 connect reset
 "$CC" "$CFLAGS" -c "$NAME2".c
 "$CC" "$CFLAGS" -c "$UTILFILE".c
 "$CC" "$CFLAGS" -o "$NAME2" "$NAME2".o "$UTILFILE".o $LIBS


